name: <Native> Assign Generated PR

on:
  pull_request_target:
    types: [closed]
    paths:
    - 'native/cocos/bindings/auto/**'

jobs:
  auto-assign:
    if: 
      (contains(github.event.pull_request.body, 'Automated PR to genbindings'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download external libraries
        env:
          PR_NUMBER: ${{github.event.number}}
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          SRC_PR=`curl ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/commits | \
            sh -c 'node ./.github/workflows/jsonr.js [0].commit.message "\(#(\w+)\)" 1'`
          SRC_MERGER=`curl -H "Accept: application/vnd.github+json" ${GITHUB_API_URL}/repos/cocos/cocos-engine/pulls/11063 | \
            sh -c 'node jsonr.js merged_by.login'`
          curl -X POST  -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $REPO_TOKEN" \
            ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees \
            -d '{"assignees":["SRC_MERGER"]}'
          exit 0